# see
#   http://docs.travis-ci.com/user/getting-started/
#   http://docs.travis-ci.com/user/languages/c/
#   http://docs.travis-ci.com/user/build-configuration/
#   http://docs.travis-ci.com/user/multi-os/
#

language: c

branches:
  only:
    - master

# matrix of compilers
compiler:
  - gcc
  - clang
  - c++

# matrix of OSes (feature flagged; not enabled now)
os:
  - linux
  - osx

# overall matrix configuration
matrix:
  allow_failures:
    - os: osx


install:
  - env | sort
  - if [ "$TRAVIS_OS_NAME" = "" ]; then TRAVIS_OS_NAME=linux; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/install-bison3.sh; sudo apt-get update -qq -y; sudo apt-get install -qq -y gtk-doc-tools libyajl-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install bison gtk-doc yajl; ln -sf /usr/local/Cellar/bison/*/bin/bison /usr/local/bin/bison; fi

script: ./autogen.sh --disable-gtk-doc && make && make test
